### PR TITLE
update link

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by waldyrious** [comment]
Also, since issues are disabled for this repo: the version of the font used by fontello may be outdated. I noticed that, for instance, the "group" icon currently at http://www.justbenice.ru/studio/websymbols is absent from the list fontello presents. There may be others, I didn't do an exhaustive check. Possibly a new version of the font was released? In that case it should be re-imported :)

**Comment by puzrin** [comment]
Website has completely different font (v2) with the same name. It can't be updated in compatible way without breaking user projects.

**Comment by puzrin** [comment]
Tag changes it ok, but link change not. It will cause a lot of confusion.

**Comment by waldyrious** [comment]
Ah, ok, so that explains the mismatch. Can you merge just the commit with the tag changes, or should I revert the link change commit?

**Comment by puzrin** [comment]
No, you need to rebase with removing wrong one

**Comment by waldyrious** [comment]
Ugh. Not in front of a console atm. I'll just send another, it's easier :P

**Pull request closed without merging**
